# Overview
In this lecture, we discuss the basics of a random number generation algorithm and how to use Python to generate random numbers. By the end of the lecture, you should be able to:

(1) Understand the basics of how a random number generator.

(2) Able to implement a linear congruential generator

(3) Understand how to use np.random.RandomState() and np.random.rand() to help generate number numbers. 

# Random number generator
A random number generator (RNG) is a device that generates a sequence of numbers or symbols that cannot be reasonably predicted better than by a random chance.

There are two ways to generate a random number:

## (1) Hardware (True) random number generator

The first way of generating random numbers relies on physical phenomena. For example, the next number generated can depend on the level of background noise in your office, the decay of radioactive sources, or even the movement of your mouse. With well-control designs, these sources will be unpredictable and not repetitive. As a result, the numbers will not start repeating the patterns after a cycle. 

True random number generator is widely used in settings that rely on high-level security, for example, banks, gambling, cybersecurity, or national defense.  

## (2) Pseudo-random number generator

The second way to generate random numbers is based on computer algorithms. Using these algorithms, we are able to generate numbers that seem to be random, although they will be repeating themselves after a cycle. A good algorithm should be able to produce a long sequence of numbers that follows a random order without repeating themselves for a long sequence.  

# Pseudo-Random Numbers
In general, a good psuedo-random number generator will fulfill the following:

The integers generated in the sequence will appear to be reasonably independent.

The integers will be roughly evenly distributed across 0, ..., m-1

The next number in the sequence can be calculated quickly.

...

In [ ]:
a = 7
m = 30
x = 3
c = 0
N = 10

#loop i through 0, 1, 2, ... N-1
for i in range(N):
    #update x
    x=(a*x+c)%m
    #generate a random number
    u=x/m
    print(u)

In [ ]:
a = 7**5
m = 2**31-1
x = 20000
c = 0
N = 10

 

#loop i through 0, 1, 2, ... N-1
for i in range(N):
    #update x
    x=(a*x+c)%m
    #generate a random number
    u=x/m
    print(u)
    

# Mersenne Twister

In [1]:
import numpy as np
#generate one random number
print(np.random.rand())
#generate an array with 1 random number
print(np.random.rand(1))
#generate an array with 10 random numbers
print(np.random.rand(10))
#generate an array with 3 rows and *2 columns
print(np.random.rand(3,2))

0.21875385307936646
[0.67734804]
[0.52383844 0.12138566 0.86889863 0.34229292 0.13502069 0.40353002
 0.0499818  0.9452394  0.06332538 0.24857977]
[[0.22589919 0.002928  ]
 [0.29913271 0.30799478]
 [0.38584561 0.33811695]]


In [2]:
import numpy as np
 
np.random.rand()
 
print(np.random.get_state())

('MT19937', array([3789333924, 4210413443, 2198512940, 2894308303, 3841070581,
        291052800,  144631975, 3695955336, 3191019372, 2373135170,
       3769311850, 4117644850, 2823906566,  833475620, 3701726026,
       1166489812, 1097986857, 1816042152,  227506654, 2246880384,
       4247927509, 1581983858, 1046549167, 1685996637, 1527367926,
       4167875197, 1917632506, 2785371961,  676684021, 2172815996,
       3179512413, 2300426809, 3996954628, 3084152373, 3658436457,
       3677224353,   34534089, 1719997468, 1430075076, 1901761934,
       3269547177, 1506521453,   66366581,  676389068, 3068961787,
       3509599609, 2624026830,  842786047, 3522033314, 3286994154,
       3820987385,  254824395, 3967207814, 2165573101, 3288297585,
       1790282881, 2358511403, 1506845398,   71902271,  197609708,
       1558983259, 3614930121, 3138472024, 3714789519, 2912315502,
       3524037677, 4067017167, 2932698070, 3442795108, 4050899069,
       1913630817, 2349573192, 2472368725, 3964406

In [3]:
import numpy as np
#generate the first number 
R1=np.random.RandomState() 
R2=np.random.RandomState() 
#generate the first random number from R1
print(R1.rand())
#generate the first random number from R2
print(R2.rand())
#generate the second random number from R1
print(R1.rand())
#generate the second random number from R2
print(R2.rand())

0.883616351834163
0.5758610681429641
0.0410325262820852
0.19629034753640517


# Generating fixed stream

## (1) Fixing the seed

In [4]:
import numpy as np
#set up the seed
np.random.seed(10)
#generate the first five numbers 
print(np.random.rand(5))
#generate next 5 five numbers 
print(np.random.rand(5))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]


## (2) Fixing RandomState 

In [5]:
import numpy as np
#generate the first random state using seed=10
R1=np.random.RandomState(seed=10)
#generate the second random state using seed=20
R2=np.random.RandomState(seed=30)
#generate the first 5 random numbers from the first stream
print(R1.rand(5))
#generate the first 5 random numbers from the second stream
print(R2.rand(5))
#generate the next 5 random numbers from the first stream
print(R1.rand(5))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.64414354 0.38074849 0.66304791 0.16365073 0.96260781]
[0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]


## (3) Using seed and RandomState at the same time.

In [6]:
import numpy as np
 
#generate the first random state using seed=10
RNG1=np.random.RandomState(seed=10)
#generate the second random state using seed=10
RNG2=np.random.RandomState(seed=10)
#generate the first 5 random numbers from the first stream
print(RNG1.rand(5))
#generate the first 5 random numbers from the second stream
print(RNG2.rand(5))
#generate the first 5 random numbers from the "global" stream
print(np.random.rand(5))
#generate the next 5 random numbers from the first stream
print(RNG1.rand(5))


[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
[0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]


# Monte-Carlo integration
In this lecture, we use the random numbers to perform an important task: Monte-Carlo integration.

Learning objective:

able to perform one-dimensional integral problems using MC integration

get familiar with list and array
 